# Generated by Django 4.1.1 on 2022-09-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=50)),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Rating')),
                ('duration', models.DurationField(verbose_name='Durex')),
            ],
        ),
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('id_pole', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
            ],
        ),
    ]
